-- MySQL Script generated by MySQL Workbench
-- Sat Apr 27 19:29:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Affinity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Affinity` ;

-- -----------------------------------------------------
-- Schema Affinity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Affinity` DEFAULT CHARACTER SET utf8 ;
USE `Affinity` ;

-- -----------------------------------------------------
-- Table `Affinity`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affinity`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Affinity`.`Usuarios` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(25) NOT NULL,
  `Ubicación` VARCHAR(45) NOT NULL,
  `Miembro` TINYINT NOT NULL,
  PRIMARY KEY (`ID_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Affinity`.`Aficiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affinity`.`Aficiones` ;

CREATE TABLE IF NOT EXISTS `Affinity`.`Aficiones` (
  `ID_aficion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID_aficion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Affinity`.`Usuario_aficion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affinity`.`Usuario_aficion` ;

CREATE TABLE IF NOT EXISTS `Affinity`.`Usuario_aficion` (
  `ID_usuario` INT NOT NULL,
  `ID_aficion` INT NOT NULL,
  INDEX `ID_usuario_idx` (`ID_usuario` ASC) VISIBLE,
  INDEX `ID_aficion_idx` (`ID_aficion` ASC) VISIBLE,
  CONSTRAINT `ID_usuario`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `Affinity`.`Usuarios` (`ID_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_aficion`
    FOREIGN KEY (`ID_aficion`)
    REFERENCES `Affinity`.`Aficiones` (`ID_aficion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO usuarios (ID_usuario, Nombre, Mail, Contrasena, Ubicacion, Miembro)
VALUES 
('00000001', 'Ana García', 'ana.garcia@mail.com', 'password123', 'Chamberí', 'SI'),
('00000002', 'Carlos Sánchez', 'carlos.sanchez@mail.com', 'securePass!', 'Salamanca', 'SI'),
('00000003', 'María López', 'maria.lopez@mail.com', 'maria2021', 'Chamartín', 'NO'),
('00000004', 'Pedro Gómez', 'pedro.gomez@mail.com', 'Pedro123', 'Retiro', 'SI'),
('00000005', 'Sofía Martínez', 'sofia.martinez@mail.com', 'S0fia!Mart', 'Centro', 'NO'),
('00000006', 'Javier Rodríguez', 'javier.rodriguez@mail.com', 'Javi2020', 'La Latina', 'SI'),
('00000007', 'Lucía Fernández', 'lucia.fernandez@mail.com', 'Lucia&2022', 'Tetuán', 'NO'),
('00000008', 'Miguel Torres', 'miguel.torres@mail.com', 'Miguel!2023', 'Moncloa-Aravaca', 'SI'),
('00000009', 'Isabel Pérez', 'isabel.perez@mail.com', 'IsaB3L!p', 'San Blas', 'NO'),
('00000010', 'Álvaro Moreno', 'alvaro.moreno@mail.com', 'aLVaRO123', 'Usera', 'SI');